### ISSUE TITLE
Add validation to `operations` endpoint

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-ledger-agent#13]
Need to do this in many places, but if a malformed event goes in, it leads to uncaught errors.

https://github.com/digitalbazaar/bedrock-ledger-agent/blob/master/lib/http.js#L251

Continuity has been using this for validation: https://github.com/digitalbazaar/bedrock-validation/tree/3.x which uses the faster more modern [ajv](https://github.com/epoberezkin/ajv)  validator.  Here is a sample schema: https://github.com/digitalbazaar/bedrock-ledger-consensus-continuity/blob/master/schemas/continuity.js

**Comment by dlongley** [comment]
We've redesigned how the validators work and I'm currently working on implementing the new design. There will be operation validators that the ledger node uses in its `operations.add` API.

**Comment by mattcollier** [comment]
It has been decided that a basic JSON schema validator on the operations endpoint would be useful.  It should check for the following:
- context
- type
- record
- record.id is a URL

**Comment by mattcollier** [comment]
@dlongley apropos of our recent discussion about validating operations I found this issue and the prior resolution about what to do.  Do you think the schema validation described above is a good idea?

**Comment by dlongley** [comment]
@mattcollier, I think we're going to end up repeating these checks in the specific operation validators, so I don't think it's necessary. It will just burn up CPU cycles, no?

**Comment by mattcollier** [comment]
I'm not sure exactly where the original code link was pointing to in http.js, however, the issue remains that there are opportunities of uncaught errors in the pipeline if some basic validation is not performed somewhere early in the process.

**Comment by dlongley** [comment]
@mattcollier,

http.js immediately calls `ledgerAgent.node.operations.add`:

https://github.com/digitalbazaar/bedrock-ledger-agent/blob/master/lib/http.js#L282

Which immediately calls the validator(s) for the node:

https://github.com/digitalbazaar/bedrock-ledger-node/blob/master/lib/ledger-node-operations.js#L29-L40

**Comment by mattcollier** [comment]
Right, I think we noted that before, but thought it would be useful to allow operationValidators to make some very basic assumptions about an operation document so that we don't require basic validation at that level.

**Comment by dlongley** [comment]
@mattcollier,

Don't we expect operation validators to include those same checks in their schemas though? (I would think so). I'm not opposed to making things easier/more robust obviously, but it just seems like we'd be wasting CPU in this particular case. Maybe it's negligible and we'd get more help than harm out of it -- is that what you think? I don't know ... but I lean towards it being unnecessary.

It may be better to have common operation schemas that we can extend in validators we write. So you get the core checks from that -- but you extend with more specific properties in the record, etc. Thoughts?

**Comment by mattcollier** [comment]
Here's the only existing validator afaik: https://github.com/veres-one/veres-one-validator/blob/master/schemas/veres-one-validator.js#L222 and it certainly has those checks.  However, by this time there have been a number of database hits to get the ledgerNode and lookup the ledgerConfig etc.  

I'm going to close this.  Adding more protection on the endpoint will be easy enough if the need should arise.
