### ISSUE TITLE
Upgrade Bedrock Ledger Agent

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-ledger-agent#33]
Test Project:
- [x] to use [`bedrock-mongodb`](https://github.com/digitalbazaar/bedrock-mongodb) >= 7.0
- [x] remove [`bedrock-identity`](https://github.com/digitalbazaar/bedrock-identity) from the project
- [x] remove `bedrock-identity` from the test project
- [x] upgrade all test deps from `npm outdated`
- [x] remove [`bedrock-key`](https://github.com/digitalbazaar/bedrock-key) from the test project
- [x] remove [`bedrock-did-client`](https://github.com/digitalbazaar/bedrock-did-client) from the test project
- [ ] upgrade [`jsonld-signatures`](https://github.com/digitalbazaar/jsonld-signatures) from `2.3.1` to `5.1.0`

Branches:
https://github.com/digitalbazaar/bedrock-ledger-agent/tree/upgrade-bedrock-mongodb-7
https://github.com/digitalbazaar/bedrock-ledger-agent/tree/update-tests

TODO:
- [x] remove backwards compatible `bedrock-identity` calls
- [x] possibly use `req.user.actor` over `req.user.account` (check changes to `bedrock-account`(https://github.com/digitalbazaar/bedrock-account) for this)
- [x] Add CHANGELOG entries
- [x] Make a major breaking Release `4.0.0`

**Comment by mattcollier** [comment]
@aljones15 can this be closed?

**Comment by aljones15** [comment]
@mattcollier yes this bedrock-ledger-agent issue can be closed. We did not quite get the version of jsigs wanted, but over that can occur in down the road.
